name: kafil
description: "private task for kafil company"

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  #ui
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  cached_network_image: ^3.3.0
  loader_overlay: ^2.2.0
  flutter_svg: ^2.0.8
  flutter_screenutil: ^5.7.0
  animate_do: ^3.1.2
  dropdown_button2: ^2.3.9
  syncfusion_flutter_sliders: ^23.1.44
  elegant_notification: ^1.11.2
  auto_size_text: ^3.0.0
  chips_input: ^0.1.0

  # State Management
  flutter_riverpod: any
  riverpod: ^2.2.0

  #remote
  dio: ^5.3.3
  json_annotation: ^4.5.0

  #local
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  #utils
  flutter_native_splash: ^2.3.4
  flutter_launcher_icons: ^0.13.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  image_picker: ^1.0.4


  #testing
  mockito: ^5.4.2

  #routing
  go_router: ^8.0.1

  #localization
  easy_localization: ^3.0.0

  # depend reference
  intl: ^0.18.0
  easy_logger: ^0.0.2

  # Debugging and Testing
  logging: ^1.1.1


dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter

  lint: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "ffffff"
  image: assets/images/logo.png
